--- 
dbdata: 
  image: "redis:latest"
  volumes: 
    - /data

db: 
  image: "redis:latest"
  ports: 
    - "6379:6379"
  volumes_from: 
    - dbdata

web: 
  build: .
  environment:
    - INTERLOCK_DATA={"hostname":"docker-training.com","domain":"docker-training.com"}
  links: 
    - "db:redis-db"
  ports: 
    - "8080"
