version: '2'
services:
  lb:
    build: haproxy
    #container_name: lb
    ports:
     - "80:80"
    networks:
      - dubdub

  db:
    image: "redis:latest"
    #container_name: db
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    networks:
      - dubdub

  web:
    build: counter-app
    #container_name: web
    environment:
      - INTERLOCK_DATA={"hostname":"docker-training.com","domain":"docker-training.com"}
    ports:
      - "8080"
    networks:
      - dubdub

networks:
  dubdub:
    driver: overlay

volumes:
  data: {}
