---
lb:
  build: haproxy
  container_name: lb0
  ports:
   - "80:80"

dbdata:
  image: "redis:latest"
  volumes: 
    - /data

db: 
  image: "redis:latest"
  ports: 
    - "6379:6379"
  volumes_from: 
    - dbdata

web: 
  build: counter-app
  links: 
    - "db:redis-db"
  environment:
    - INTERLOCK_DATA={"hostname":"docker-training.com","domain":"docker-training.com"}
  ports: 
    - "8080"
