--- 
dbdata: 
  image: "redis:latest"
  volumes: 
    - /data

db: 
  image: "redis:latest"
  ports: 
    - "6379"
  volumes_from: 
    - dbdata

web: 
  build: .
  links: 
    - "db:redis-db"
  ports: 
    - "8080"
