---
db: 
  image: "redis:latest"
  ports: 
    - "6379:6379"
  volumes: 
    - /data:/data

web: 
  build: .
  links: 
    - "db:redis-db"
  environment:
    - INTERLOCK_DATA={"hostname":"docker-training.com","domain":"docker-training.com"}
  ports: 
    - "8080"
